### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by GalaxiumNation** [killjoy1221/HD-Font-Generator#15]
gradlew.bat installs files, and stops

**Comment by mattmess1221** [comment]
I would suggest downloading the [pre-built binaries](../releases/latest).

Otherwise, if you are simply running it locally from source, you can run `./gradlew run` to run the project with gradle. If you really want to build from source, final executables should be in `build/distributions`.

Quick overview of the main tasks

- `./gradlew run` - Runs the project with gradle
- `./gradlew build` - Build the project and package dependencies with a launch script. This is useful if you have the JDK installed already, though you have to extract it manually.
- `./gradlew jPackageDist` - Create a platform-specific archive which bundles the JRE. The unarchived build files are located in `build/jpackage`.

I've added this to the README via df4e42f21962d5cdf97617e76e0d954e61bae583
